CREATE PROCEDURE SP_ELIMINAR_LISTA_RECOMENDADA(
	@ID UNIQUEIDENTIFIER
)AS
BEGIN
	BEGIN
		DELETE FROM [dbo].ListaxVideo
		WHERE IdLista = @ID
		
		DELETE FROM ListasRecomendados
		WHERE Id = @ID
	END
END